Release task

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -257,3 +257,53 @@ tasks:
     desc: format frontend code
     dir: ui.frontend
     cmd: sh npmw run format
+
+  release:
+    desc: release AEM packages
+    cmd: |
+      VERSION="{{.CLI_ARGS}}"
+      VERSION_TAG="v$VERSION"
+
+      VERSION_CURRENT_TAG=$(git describe --tags --abbrev=0)
+      VERSION_CURRENT_TAG="${VERSION_CURRENT_TAG:1}"
+
+      if [ -z "$VERSION" ]
+      then
+            echo "Release version is not specified!"
+            echo "Last released: ${VERSION_CURRENT_TAG}"
+            exit 1
+      fi
+
+      GIT_STAT=$(git diff --stat)
+
+      if [ "$GIT_STAT" != '' ]; then
+        echo "Unable to release. Uncommitted changes detected!"
+        exit 1
+      fi
+
+      echo "Releasing $VERSION_TAG"
+
+      echo "Bumping version in files"
+
+      echo "<TODO>"
+      #README_FILE="README.MD"
+      #PROJECT_WRAPPER_SCRIPT="pkg/project/common/aemw"
+      #
+      ## <https://stackoverflow.com/a/57766728>
+      #if [ "$(uname)" = "Darwin" ]; then
+      #  sed -i '' 's/AEM_CLI_VERSION:-"[^\"]*"/AEM_CLI_VERSION:-"'"$VERSION"'"/g' "$PROJECT_WRAPPER_SCRIPT"
+      #  # shellcheck disable=SC2016
+      #  sed -i '' 's/aem\@v[^\`]*\`/aem@v'"$VERSION"\`'/g' "$README_FILE"
+      #else
+      #    sed -i 's/AEM_CLI_VERSION:-"[^\"]*"/AEM_CLI_VERSION:-"'"$VERSION"'"/g' "$PROJECT_WRAPPER_SCRIPT"
+      #    # shellcheck disable=SC2016
+      #    sed -i 's/aem\@v[^\`]*\`/aem@v'"$VERSION"\`'/g' "$README_FILE"
+      #fi
+
+      echo "Pushing version bump"
+      git commit -a -m "Release $VERSION_TAG"
+      git push
+
+      echo "Pushing release tag '$VERSION_TAG'"
+      git tag "$VERSION_TAG"
+      git push origin "$VERSION_TAG"
